### ISSUE TITLE
[Feature Request] Ability to Favorite/Pin/Star Instances

### ISSUE THREAD

**Issue by nxrmqlly** [gorilla-devs/GDLauncher-Carbon#369]
The title says it all. We should be able to favorite/star/pin instances so that they stay on top of the list and also cannot be accidentally deleted (+ more features, perhaps). At the very least we should be able to drag-n-drop the instances to change the layout they are displayed in.

**Comment by MrT-tak** [comment]
?

**Comment by nxrmqlly** [comment]
?


________________________________

**Comment by nxrmqlly** [comment]
Sorry, I didnt realise this was already implemented

________________________________
