### ISSUE TITLE
Latest Release (1.21.4)  is missing for "Add Instance"

### ISSUE THREAD

**Issue by EtlamGit** [gorilla-devs/GDLauncher-Carbon#386]
I just downloaded/installed GDlauncher-Carbon on a fresh installed Linux Laptop.

When I try to create a new instance with latest Minecraft Release, only 1.21.3 is offered.
With snapshots enabled, the latest is 1.21.4-pre1 from 2024-11-20.

Where does this information come from?
Is there any file I can change to support more recent versions?

**Comment by staridiot** [comment]
Honestly it may be worth just using the Vanilla launcher and dealing with profiles/modpacks manually. I haven't found a launcher that doesn't rely on the launcher's maintainers to add vanilla versions of Minecraft (among other things). This one looked promising but this is probably the nail in the coffin for me.

**Comment by EtlamGit** [comment]
Today version 1.21.4 showed up!
Vanilla instance is working, Fabric instance of 1.21.4 not.

So there might be an update mechanism that only runs every 24 hours?
Or someone has provided an update in the last hours?

I would like to know how I could help in case this happens again. Either changing a local file, forcing an update or providing a PR to another repo (which I do not know now).

**Comment by blarfoon** [comment]
The metadata is fetched from our own mirror, powered by https://github.com/gorilla-devs/daedalus, and it runs every 60 minutes.

Unfortunately it crashed a couple weeks ago due to neoforge changing the data type of a value, and I just fixed it yesterday.

**Comment by EtlamGit** [comment]
ok, thanks.
I assume as long as your mirror is running this issue is solved.

My remaining issue with Fabric is handled in #383 so I close this one.
